### ISSUE TITLE
nobrainer demo fails

### ISSUE THREAD

**Issue by ghazel** [gritzko/swift#4]
```
Root hash: d1502706c46779d361a1d562a10da0a45c4c40e5
done 0 of 0 (seq 0) 1 dgram 34 bytes up, 0 dgram 0 bytes down
done 0 of 0 (seq 0) 2 dgram 68 bytes up, 0 dgram 0 bytes down
done 0 of 0 (seq 0) 3 dgram 102 bytes up, 0 dgram 0 bytes down
done 0 of 0 (seq 0) 4 dgram 136 bytes up, 0 dgram 0 bytes down
done 0 of 0 (seq 0) 5 dgram 170 bytes up, 0 dgram 0 bytes down
done 0 of 0 (seq 0) 6 dgram 204 bytes up, 0 dgram 0 bytes down
done 0 of 0 (seq 0) 6 dgram 204 bytes up, 0 dgram 0 bytes down
done 0 of 0 (seq 0) 7 dgram 238 bytes up, 0 dgram 0 bytes down
done 0 of 0 (seq 0) 8 dgram 272 bytes up, 0 dgram 0 bytes down
done 0 of 0 (seq 0) 9 dgram 306 bytes up, 0 dgram 0 bytes down
done 0 of 0 (seq 0) 10 dgram 340 bytes up, 0 dgram 0 bytes down
done 0 of 0 (seq 0) 10 dgram 340 bytes up, 0 dgram 0 bytes down
done 0 of 0 (seq 0) 10 dgram 340 bytes up, 0 dgram 0 bytes down
done 0 of 0 (seq 0) 10 dgram 340 bytes up, 0 dgram 0 bytes down
```

...

**Comment by gritzko** [comment]
Hi! It is totally unclear what happens; please provide the command line. Also, the root hash must be a SHA1 hash. Check the README.
BTW, one early common pitfall is that the default IP is 127.0.0.1, not 0.0.0.0.

**Comment by gritzko** [comment]
Hi Greg!

I think, I remember that once I've made a demo executable named "nobrainer". It was made in March 2010, I believe. All IPs and hashes were hardcoded, not sure to what particular values. Where did you get it?
Otherwise, you'd better compile the project and use the swift executable. Some examples are provided in the README, also ./swift --help prints out usage info.
Thanks for your interest,

```
              Victor
```

**Comment by ghazel** [comment]
It is linked to here: http://libswift.org/

In "Downloads":

One-click demo for Windows: swift-nobrainer.exe

http://97.107.136.211/files/swift-nobrainer.exe
